#############################################################################
# Makefile for building: FacElectronica
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  FacElectronica.pro
# Template: subdirs
# Command: D:\Qt\Qt5.4.0\5.4\mingw491_32\bin\qmake.exe -spec win32-g++ CONFIG+=debug -o Makefile FacElectronica.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:\Qt\Qt5.4.0\5.4\mingw491_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src


sub-src-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd src\ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-src-make_first-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-src-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-src-all-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-src-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-src-clean-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-distclean-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-src-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets-ordered: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-src-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: FacElectronica.pro ../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/win32-g++/qmake.conf ../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/spec_pre.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/qdevice.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/device_config.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/common/shell-win32.conf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/qconfig.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axbase.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axserver.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_core.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_help.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_location.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_network.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_script.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_winextras.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/qt_functions.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/qt_config.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/win32/qt_config.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/win32-g++/qmake.conf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/spec_post.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/exclusive_builds.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/default_pre.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/win32/default_pre.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/resolve_config.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/exclusive_builds_post.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/default_post.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/win32/rtti.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/precompile_header.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/warn_on.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/win32/windows.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/testcase_targets.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/exceptions.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/yacc.prf \
		../../Qt/Qt5.4.0/5.4/mingw491_32/mkspecs/features/lex.prf \
		FacElectronica.pro
	$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile FacElectronica.pro
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\spec_pre.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\qdevice.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\device_config.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\common\shell-win32.conf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\qconfig.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axbase.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axserver.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_concurrent.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_core.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_core_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_declarative.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_declarative_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_designer.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_designer_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_enginio.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_enginio_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_gui.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_gui_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_help.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_help_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_location.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_location_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_multimedia.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_network.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_network_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_nfc.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_opengl.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_positioning.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_printsupport.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qml.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qml_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qmltest.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_quick.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_quick_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_script.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_script_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_scripttools.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_sensors.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_serialport.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_sql.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_sql_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_svg.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_svg_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_testlib.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_uitools.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webchannel.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webkit.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webkit_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_websockets.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webview.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_webview_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_widgets.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_winextras.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_xml.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_xml_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\qt_functions.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\qt_config.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\win32\qt_config.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\win32-g++\qmake.conf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\spec_post.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\exclusive_builds.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\default_pre.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\win32\default_pre.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\resolve_config.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\exclusive_builds_post.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\default_post.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\win32\rtti.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\precompile_header.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\warn_on.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\win32\windows.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\testcase_targets.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\exceptions.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\yacc.prf:
..\..\Qt\Qt5.4.0\5.4\mingw491_32\mkspecs\features\lex.prf:
FacElectronica.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile FacElectronica.pro

qmake_all: sub-src-qmake_all FORCE

make_first: sub-src-make_first-ordered FORCE
all: sub-src-all-ordered FORCE
clean: sub-src-clean-ordered FORCE
distclean: sub-src-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets-ordered FORCE
uninstall_subtargets: sub-src-uninstall_subtargets-ordered FORCE

sub-src-debug_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-src-debug_ordered

sub-src-release_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
release: sub-src-release_ordered

sub-src-check_ordered:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) D:\dev\facelec\src\src.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

